/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './content/**/*.{md,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        fg: 'var(--color-fg)',
        muted: 'var(--color-muted)',
        faint: 'var(--color-faint)',
        line: 'var(--color-line)',
        accent: 'var(--color-accent)',
        'accent-2': 'var(--color-accent-2)',
      },
      fontFamily: {
        display: ['var(--font-newsreader)', 'Georgia', 'serif'],
        sans: ['var(--font-ibm-plex-sans)', '-apple-system', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        md: '8px',
      },
      maxWidth: {
        prose: '68ch',
        copy: '780px',
        feed: '1120px',
      },
      transitionTimingFunction: {
        'out-quart': 'cubic-bezier(0.25, 1, 0.5, 1)',
      },
      typography: ({ theme }) => {
        const shared = {
          '--tw-prose-body': 'var(--color-fg)',
          '--tw-prose-headings': 'var(--color-fg)',
          '--tw-prose-links': 'var(--color-accent)',
          '--tw-prose-bold': 'var(--color-fg)',
          '--tw-prose-quotes': 'var(--color-fg)',
          '--tw-prose-quote-borders': 'var(--color-accent)',
          '--tw-prose-captions': 'var(--color-muted)',
          '--tw-prose-code': 'var(--color-fg)',
          '--tw-prose-hr': 'var(--color-line)',
          '--tw-prose-th-borders': 'var(--color-line)',
          '--tw-prose-td-borders': 'var(--color-line)',
          '--tw-prose-invert-body': 'var(--color-fg)',
          '--tw-prose-invert-headings': 'var(--color-fg)',
          '--tw-prose-invert-links': 'var(--color-accent)',
          '--tw-prose-invert-bold': 'var(--color-fg)',
          '--tw-prose-invert-quotes': 'var(--color-fg)',
          '--tw-prose-invert-quote-borders': 'var(--color-accent)',
          '--tw-prose-invert-captions': 'var(--color-muted)',
          '--tw-prose-invert-code': 'var(--color-fg)',
          '--tw-prose-invert-hr': 'var(--color-line)',
          '--tw-prose-invert-th-borders': 'var(--color-line)',
          '--tw-prose-invert-td-borders': 'var(--color-line)',
          maxWidth: '68ch',
          fontSize: '21px',
          lineHeight: '1.72',
          fontFamily: theme('fontFamily.display').join(', '),
          h1: { fontFamily: theme('fontFamily.display').join(', '), fontWeight: '560', letterSpacing: '-0.024em' },
          h2: {
            fontFamily: theme('fontFamily.display').join(', '),
            fontWeight: '600',
            fontSize: '31px',
            lineHeight: '1.15',
            letterSpacing: '-0.01em',
            marginTop: '46px',
            marginBottom: '20px',
          },
          h3: { fontFamily: theme('fontFamily.display').join(', '), fontWeight: '600' },
          a: { textDecoration: 'none', borderBottom: '1px solid var(--color-accent)', fontWeight: '400' },
          'a:hover': { color: 'var(--color-accent-2)' },
          blockquote: {
            borderLeftWidth: '2px',
            paddingLeft: '30px',
            paddingTop: '6px',
            paddingBottom: '6px',
            fontFamily: theme('fontFamily.display').join(', '),
            fontStyle: 'italic',
            fontSize: '29px',
            lineHeight: '1.32',
            letterSpacing: '-0.012em',
            color: 'var(--color-fg)',
          },
          'blockquote p:first-of-type::before': { content: 'none' },
          'blockquote p:last-of-type::after': { content: 'none' },
          code: {
            fontFamily: theme('fontFamily.mono').join(', '),
            backgroundColor: 'var(--color-surface)',
            padding: '0.2em 0.4em',
            borderRadius: '4px',
            fontWeight: '400',
          },
          'code::before': { content: 'none' },
          'code::after': { content: 'none' },
          pre: {
            backgroundColor: '#0f0d0c',
            color: '#f1eeec',
            borderRadius: '4px',
          },
          'pre code': {
            backgroundColor: 'transparent',
            color: 'inherit',
            padding: '0',
            fontWeight: '400',
          },
        }

        const table = {
          table: {
            fontVariantNumeric: 'tabular-nums',
          },
          thead: {
            borderBottomWidth: '1px',
            borderBottomColor: 'var(--color-line)',
          },
          'thead th': {
            fontFamily: theme('fontFamily.mono').join(', '),
            fontSize: '0.8125rem',
            fontWeight: '500',
            letterSpacing: '0.02em',
            color: 'var(--color-muted)',
            paddingTop: '0',
            paddingBottom: '0.75em',
            paddingInlineStart: '1.5em',
            paddingInlineEnd: '1.5em',
          },
          'thead th:first-child': { paddingInlineStart: '0' },
          'thead th:last-child': { paddingInlineEnd: '0' },
          'tbody tr': {
            borderBottomWidth: '1px',
            borderBottomColor: 'var(--color-line)',
          },
          'tbody tr:last-child': { borderBottomWidth: '0' },
          'tbody td': {
            paddingTop: '0.75em',
            paddingBottom: '0.75em',
            paddingInlineStart: '1.5em',
            paddingInlineEnd: '1.5em',
          },
          'tbody td:first-child': { paddingInlineStart: '0' },
          'tbody td:last-child': { paddingInlineEnd: '0' },
          'thead th:not(:first-child), tbody td:not(:first-child)': {
            textAlign: 'right',
          },
        }

        return {
          DEFAULT: { css: { ...shared, ...table } },
          invert: { css: { ...shared, ...table } },
          lg: { css: table },
        }
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
